# Generated by Django 3.1.3 on 2020-11-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestor',
            name='birth_document',
            field=models.FileField(default='', upload_to='ancestor_files'),
            preserve_default=False,
        ),
    ]
