# Generated by Django 3.1.3 on 2020-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
