# Generated by Django 3.1.3 on 2020-12-15 09:29

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('people', '0002_auto_20201211_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_published']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_of_birth',
            new_name='year_of_birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_of_death',
            new_name='year_of_death',
        ),
        migrations.AddField(
            model_name='person',
            name='abstract',
            field=models.TextField(default='Default abstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_published',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='Default slug', editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
